"""Quantize a checkpoint's decoder, run the gate, and write the shipped weights + parity fixtures.

Usage: python export.py --checkpoint runs/baseline/best.pt
       python export.py --checkpoint runs/x/best.pt --skip-gate --out test-results/candidate.ts
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

import evaluate
import model
import quantize
import sprite
from data import DATA_DIR, load_dataset
from seed import SEED_VERSION, latents_for_seeds

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
ACTIVE_DIR = HERE / "active"
DEFAULT_OUT = REPO / "packages" / "core" / "src" / "model" / "weights.ts"
CORE_SRC = REPO / "packages" / "core" / "src"
PARITY_SEEDS = 64


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def checkpoint_label(path: Path) -> str:
    return f"{path.parent.name}@{sha256_file(path)[:12]}"


def render_weights_ts(qspec: dict, checkpoint: str) -> str:
    layers = []
    for l in qspec["layers"]:
        bias = ", ".join(quantize.f32_repr(b) for b in l["bias"])
        layers.append(
            f'    {{ "in": {l["in"]}, "out": {l["out"]}, "activation": "{l["activation"]}", '
            f'"scale": {quantize.f32_repr(l["scale"])}, "bias": [{bias}] }}'
        )
    return (
        "// GENERATED by packages/training/export.py. Do not edit by hand.\n"
        f"// checkpoint: {checkpoint}\n"
        'import type { ModelSpec } from "./types.ts";\n\n'
        "export const model: ModelSpec = {\n"
        f"  format: {qspec['format']},\n"
        f"  seedVersion: {qspec['seedVersion']},\n"
        f"  latent: {qspec['latent']},\n"
        f'  checkpoint: "{checkpoint}",\n'
        "  layers: [\n" + ",\n".join(layers) + "\n  ],\n"
        f'  weights: "{quantize.pack_weights_base64(qspec)}",\n'
        "};\n"
    )


def build_parity(qspec: dict, seeds) -> dict:
    latent = int(qspec["latent"])
    entries = []
    for seed in seeds:
        # A sequential generator of width `latent` yields exactly this prefix of the 32-dim seed stream.
        z = latents_for_seeds([seed])[:, :latent][0]
        logits = quantize.forward_sequential(qspec, z)
        bits = (logits > 0).astype(np.uint8)
        entries.append({
            "seed": int(seed),
            "z": [float(v) for v in z],
            "logits": [float(v) for v in logits],
            # Raw threshold, and the final sprite after isolated-pixel cleanup.
            "bits": np.packbits(bits).tobytes().hex(),
            "sprite": np.packbits(sprite.logits_to_sprites(logits)).tobytes().hex(),
            "minMargin": float(np.abs(logits).min()),
        })
    return {"seedVersion": SEED_VERSION, "latent": latent, "pixels": 256, "entries": entries}


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--checkpoint", required=True)
    p.add_argument("--out", default=str(DEFAULT_OUT))
    p.add_argument("--skip-gate", action="store_true")
    p.add_argument("--data-dir", default=str(DATA_DIR))
    p.add_argument("--seeds", type=int, default=1000)
    a = p.parse_args(argv)
    out = Path(a.out).resolve()
    if a.skip_gate and CORE_SRC in out.parents:
        print(f"--skip-gate cannot write inside {CORE_SRC}; pass --out with a path outside src/", file=sys.stderr)
        sys.exit(2)
    ckpt = Path(a.checkpoint)
    if not ckpt.exists():
        print(f"checkpoint not found: {ckpt}", file=sys.stderr)
        sys.exit(2)

    vae, config, extra = model.load_checkpoint(ckpt)
    qspec = quantize.quantize_decoder(vae.decoder.layer_specs())
    label = checkpoint_label(ckpt)

    gate = None
    if not a.skip_gate:
        gate = evaluate.evaluate_checkpoint(ckpt, Path(a.data_dir), a.seeds)
        evaluate.print_result(gate)
        if not gate["passed"]:
            print("gate failed; nothing written", file=sys.stderr)
            return 1

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_weights_ts(qspec, label), newline="\n")
    parity = {"checkpoint": label, **build_parity(qspec, range(PARITY_SEEDS))}
    print(f"wrote {out} ({out.stat().st_size} bytes)")

    if a.skip_gate:
        (out.parent / "parity.json").write_text(json.dumps(parity) + "\n")
        print("candidate export; active/ not updated")
        return 0

    train_np, val_np, stats = load_dataset(Path(a.data_dir))
    train_sha256 = hashlib.sha256(train_np.tobytes()).hexdigest()
    val_sha256 = hashlib.sha256(val_np.tobytes()).hexdigest()
    ACTIVE_DIR.mkdir(exist_ok=True)
    (ACTIVE_DIR / "parity.json").write_text(json.dumps(parity) + "\n")
    training_report = json.loads((ckpt.parent / "report.json").read_text()) if (ckpt.parent / "report.json").exists() else {}
    report = {
        "checkpoint": label,
        "exported_at": datetime.now(timezone.utc).isoformat(),
        "gate": gate,
        "floors": {"reconstruction": gate["recon_floor"]},
        "data": {**stats, "train_sha256": train_sha256, "val_sha256": val_sha256},
        "training": {k: v for k, v in training_report.items() if k != "epochs"},
        "quantization": {"scheme": "int8 symmetric per-tensor", "layers": [{"in": l["in"], "out": l["out"], "scale": float(l["scale"])} for l in qspec["layers"]]},
        "decoder_parameters": gate["decoder_parameters"],
    }
    (ACTIVE_DIR / "report.json").write_text(json.dumps(report, indent=2) + "\n")
    manifest = {
        "checkpoint": label,
        "checkpoint_sha256": sha256_file(ckpt),
        "train_sha256": train_sha256,
        "val_sha256": val_sha256,
        "weights_ts_sha256": sha256_file(out),
        "parity_seeds": PARITY_SEEDS,
        "exported_at": report["exported_at"],
    }
    (ACTIVE_DIR / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"promoted {label}; active/ updated")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
